name:                MC346-projeto
version:             0.2.0.0
github:              "TiagodePAlves/MC346-projeto-haskell"
license:             MIT
author:              "Tiago de Paula, João Pedro de Amorim"
maintainer:          "tiagodepalves@gmail.com, joaopedrodeamorin@gmail.com"
copyright:           "2019 Tiago de Paula, João Pedro de Amorim"

extra-source-files:
- README.md

description:
    Projeto de Haskell - Paradigmas de Programação [MC346].
    Mais detalhes no README <https://github.com/TiagodePAlves/MC346-projeto-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
    source-dirs:
    - lib
